RESTApi Standards
AdamSlack/stroke_drivers_screening_assessment pull request #5
Opened 2017-11-28 16:40 UTC by deanott

Here is the complete standards for the api

Issues:
* error codes
* Oauth research

2017-11-29 14:11 UTC, User4012 requested changes
There are a number of endpoints using participant ID that should be using test ID. There are also some other issues. I will make a copy of this and make some changes

2017-11-30 17:50 UTC, AdamSlack reviewed
sure,

its just a .md so it doesn't matter too much.

2017-11-30 17:50 UTC, AdamSlack approved these changes

2017-11-30 17:51 UTC, AdamSlack approved these changes

2017-11-30 17:52 UTC, merged